#!/usr/bin/env python3
"""
Fluency Scorer Script - Calculate fluency score from raw analysis input data

Takes analysis data from JSON file generated by analyzer.py (containing raw input metrics)
and calculates fluency score (0-100) with detailed subscore breakdowns.

Self-contained implementation with all scoring logic embedded directly.
"""

import json
import sys
from pathlib import Path
from typing import Tuple, Dict, List


# ============================================================
# SCORING CONFIGURATION CONSTANTS
# ============================================================

# Speech rate thresholds
WPM_TOO_SLOW = 70
WPM_SLOW_THRESHOLD = 110
WPM_OPTIMAL_MAX = 170
WPM_FAST_DECAY_RANGE = 120

# Pause and filler limits
MAX_LONG_PAUSES_PER_MIN = 4.0
MAX_FILLERS_PER_MIN = 6.0

# Scoring thresholds
PAUSE_SCORE_BLOCK_THRESHOLD = 0.6
FILLER_SCORE_BLOCK_THRESHOLD = 0.6
STABILITY_SCORE_WARN_THRESHOLD = 0.6
LEXICAL_LOW_THRESHOLD = 0.5

# Rhythmic stability
BASE_PAUSE_VARIABILITY = 0.7

# Scoring weights (sum = 1.0)
WEIGHT_PAUSE = 0.30
WEIGHT_FILLER = 0.25
WEIGHT_STABILITY = 0.20
WEIGHT_SPEECH_RATE = 0.15
WEIGHT_LEXICAL = 0.10

# Context configuration
CONTEXT_CONFIG = {
    "conversational": {
        "pause_tolerance": 1.0,
        "pause_variability_tolerance": 1.0,
    },
    "ielts": {
        "pause_tolerance": 1.0,
        "pause_variability_tolerance": 1.0,
    },
    "narrative": {
        "pause_tolerance": 1.4,
        "pause_variability_tolerance": 1.3,
    },
    "presentation": {
        "pause_tolerance": 1.2,
        "pause_variability_tolerance": 1.1,
    },
    "interview": {
        "pause_tolerance": 0.9,
        "pause_variability_tolerance": 0.9,
    },
}

# Action plan instructions for detected issues
INSTRUCTIONS = {
    "hesitation_structure": "Pause only after completing full clauses or ideas.",
    "filler_dependency": "Replace filler words with silent pauses under 300 ms.",
    "delivery_instability": "Practice steady pacing using metronome or rhythm drills.",
    "delivery_pacing": "Reduce speaking speed slightly while maintaining energy.",
    "lexical_simplicity": "Actively substitute repeated words during rehearsal.",
}

# ============================================================
# SCORING FUNCTIONS (EMBEDDED)
# ============================================================

def clamp01(x: float) -> float:
    """Clamp value to [0, 1] range."""
    return max(0.0, min(1.0, x))


def calculate_subscores(
    metrics: dict,
    context_config: dict
) -> Tuple[dict, dict]:
    """
    Calculate fluency subscores from raw input metrics.

    Args:
        metrics: Normalized metrics dictionary
        context_config: Context-specific tolerance settings

    Returns:
        Tuple of (subscores dict, context dict)
    """
    wpm = metrics["wpm"]

    # Speech rate score
    if wpm < WPM_SLOW_THRESHOLD:
        speech_rate_score = clamp01(
            (wpm - WPM_TOO_SLOW) / (WPM_SLOW_THRESHOLD - WPM_TOO_SLOW)
        )
    elif wpm <= WPM_OPTIMAL_MAX:
        speech_rate_score = 1.0
    else:
        speech_rate_score = clamp01(
            1 - (wpm - WPM_OPTIMAL_MAX) / WPM_FAST_DECAY_RANGE
        )

    # =====================================================
    # IMPROVEMENT 1: Weight pause penalty by variability
    # If pauses vary a lot, some are likely very long
    # =====================================================
    pause_variability = metrics.get("pause_variability", 0)
    long_pauses = metrics["long_pauses_per_min"]

    # Variability amplifier: high variability = more weight to pause penalty
    # Range: 1.0 (low variability) to 2.0 (high variability)
    variability_amplifier = 1.0 + clamp01(pause_variability / BASE_PAUSE_VARIABILITY)

    pause_score = clamp01(
        1 - (
            (long_pauses * variability_amplifier)
            / (MAX_LONG_PAUSES_PER_MIN * context_config["pause_tolerance"])
        )
    )

    # Filler dependency score
    filler_score = clamp01(
        1 - (metrics["fillers_per_min"] / MAX_FILLERS_PER_MIN)
    )

    # =====================================================
    # IMPROVEMENT 2: Integrate speech_rate_variability
    # Stability = control of both pauses AND speech rate
    # =====================================================
    speech_rate_variability = metrics.get("speech_rate_variability", 0)

    # Average the two variability measures
    # Normalize speech_rate_variability similar to pause_variability
    combined_variability = (pause_variability + speech_rate_variability) / 2

    stability_score = clamp01(
        1 - (
            combined_variability
            / (BASE_PAUSE_VARIABILITY * context_config["pause_variability_tolerance"])
        )
    )

    # =====================================================
    # IMPROVEMENT 3: Better lexical quality scoring
    # Use both vocab_richness and type_token_ratio
    # =====================================================
    vocab_richness = metrics.get("vocab_richness", 0)
    type_token_ratio = metrics.get("type_token_ratio", 0)
    repetition_ratio = metrics.get("repetition_ratio", 0)
    mean_utterance_length = metrics.get("mean_utterance_length", 0)

    # Combine vocab richness and type-token ratio
    # (they measure similar things, so average them)
    vocab_score = (vocab_richness + type_token_ratio) / 2

    # Reduce repetition impact
    no_repetition_score = 1 - repetition_ratio

    # Utterance length indicates syntactic complexity/confidence
    # 0-20 words = simple/choppy, 40+ words = complex/confident
    # Score 0.0 at <10 words, 1.0 at ≥40 words
    utterance_confidence = clamp01((mean_utterance_length - 10) / 30)

    lexical_score = clamp01(
        0.50 * vocab_score +           # Vocabulary richness (both measures)
        0.35 * no_repetition_score +    # Avoid repetition
        0.15 * utterance_confidence     # Syntactic complexity shows confidence
    )

    subscores = {
        "speech_rate": speech_rate_score,
        "pause": pause_score,
        "filler": filler_score,
        "stability": stability_score,
        "lexical": lexical_score,
    }

    return subscores, context_config


def apply_compound_penalties(subscores: dict, metrics: dict) -> float:
    """
    Penalize combinations of issues that humans perceive
    as 'loss of control', even if each metric alone is acceptable.
    """
    penalty = 0.0

    # Lost-control pattern: hesitation + instability + repetition
    if (
        subscores["filler"] < 0.75 and
        subscores["stability"] < 0.75 and
        metrics["repetition_ratio"] > 0.06
    ):
        penalty += 0.12

    # Fluent-but-annoying: smooth but filler-heavy
    if (
        subscores["pause"] > 0.8 and
        metrics["fillers_per_min"] > 3.0
    ):
        penalty += 0.08

    return penalty


def calculate_fluency_score(
    subscores: dict, metrics: dict
) -> int:
    """
    Calculate overall fluency score (0-100).

    Args:
        subscores: Dictionary of individual subscores
        metrics: Raw input metrics

    Returns:
        Fluency score as integer (0-100)
    """
    raw_score = (
        WEIGHT_PAUSE * subscores["pause"] +
        WEIGHT_FILLER * subscores["filler"] +
        WEIGHT_STABILITY * subscores["stability"] +
        WEIGHT_SPEECH_RATE * subscores["speech_rate"] +
        WEIGHT_LEXICAL * subscores["lexical"]
    )

    penalty = apply_compound_penalties(subscores, metrics)
    raw_score = max(0.0, raw_score - penalty)

    return int(round(100 * clamp01(raw_score)))


def detect_issues(
    subscores: dict,
    metrics: dict
) -> List[dict]:
    """
    Detect and categorize fluency issues.

    Args:
        subscores: Dictionary of subscores
        metrics: Normalized metrics

    Returns:
        List of issue dictionaries sorted by score impact
    """
    issues = []

    def issue(severity: str, issue_id: str, root_cause: str, score_impact: int):
        return {
            "issue": issue_id,
            "severity": severity,
            "root_cause": root_cause,
            "score_impact": score_impact,
        }

    # Structural blockers
    if subscores["pause"] < PAUSE_SCORE_BLOCK_THRESHOLD:
        issues.append(issue(
            "high",
            "hesitation_structure",
            "Pauses frequently interrupt sentence flow.",
            int((1 - subscores["pause"]) * 30),
        ))

    if subscores["filler"] < FILLER_SCORE_BLOCK_THRESHOLD:
        issues.append(issue(
            "high",
            "filler_dependency",
            "Fillers replace silent planning pauses.",
            int((1 - subscores["filler"]) * 25),
        ))

    if subscores["stability"] < STABILITY_SCORE_WARN_THRESHOLD:
        issues.append(issue(
            "medium",
            "delivery_instability",
            "Speech rhythm varies unpredictably.",
            int((1 - subscores["stability"]) * 20),
        ))

    # Style issues
    if subscores["speech_rate"] < 0.7:
        issues.append(issue(
            "medium",
            "delivery_pacing",
            "Speech rate deviates from optimal clarity range.",
            int((1 - subscores["speech_rate"]) * 15),
        ))

    if subscores["lexical"] < LEXICAL_LOW_THRESHOLD:
        issues.append(issue(
            "low",
            "lexical_simplicity",
            "Frequent reuse of common vocabulary.",
            int((1 - subscores["lexical"]) * 10),
        ))

    return sorted(issues, key=lambda x: x["score_impact"], reverse=True)


# ============================================================
# MAIN SCORING LOGIC
# ============================================================

def load_analysis(json_path: str) -> dict:
    """Load analysis data from JSON file."""
    json_file = Path(json_path)

    # If relative path, look in analysis directory
    if not json_file.is_absolute() and not json_file.exists():
        research_dir = Path(__file__).parent
        json_file = research_dir / "analysis" / json_path
        if not json_file.exists():
            # Try with .json extension
            json_file = research_dir / "analysis" / f"{json_path}.json"

    if not json_file.exists():
        raise FileNotFoundError(f"Analysis file not found: {json_file}")

    with open(json_file, 'r') as f:
        return json.load(f)


def calculate_fluency(analysis_data: dict) -> dict:
    """
    Calculate fluency score from raw input metrics.

    Args:
        analysis_data: Dictionary from analyzer output (contains input_metrics)

    Returns:
        Dictionary with fluency score and subscores
    """
    # Extract raw input metrics
    metrics = analysis_data.get("input_metrics", {})

    if not metrics:
        raise ValueError("Missing 'input_metrics' in analysis data")

    # Use conversational context config
    context_config = CONTEXT_CONFIG.get("conversational", {
        "pause_tolerance": 1.0,
        "pause_variability_tolerance": 1.0,
    })

    # Calculate subscores from raw input metrics
    subscores, _ = calculate_subscores(metrics, context_config)

    # Calculate overall fluency score
    fluency_score = calculate_fluency_score(subscores, metrics)

    # Detect issues
    issues = detect_issues(subscores, metrics)

    return {
        "fluency_score": fluency_score,
        "subscores": subscores,
        "issues": issues,
        "input_metrics": metrics,
    }


def format_fluency_report(score_result: dict, analysis_data: dict) -> str:
    """Format fluency scoring results for display."""
    lines = []

    filename = analysis_data.get("metadata", {}).get("filename", "Unknown")
    lines.append(f"Fluency Analysis Report")
    lines.append(f"File: {filename}")
    lines.append("=" * 70)

    # Fluency score
    fluency_score = score_result.get("fluency_score", 0)
    lines.append(f"\nFluency Score: {fluency_score}/100")
    lines.append("-" * 70)

    # Subscores
    subscores = score_result.get("subscores", {})
    if subscores:
        lines.append("\nSubscores (0.0-1.0):")
        lines.append(f"  Speech Rate:       {subscores.get('speech_rate', 0):.2f}")
        lines.append(f"  Pause Structure:   {subscores.get('pause', 0):.2f}")
        lines.append(f"  Filler Dependency: {subscores.get('filler', 0):.2f}")
        lines.append(f"  Rhythmic Stability:{subscores.get('stability', 0):.2f}")
        lines.append(f"  Lexical Quality:   {subscores.get('lexical', 0):.2f}")

    # Input metrics used for calculation
    metrics = score_result.get("input_metrics", {})
    if metrics:
        lines.append("\nInput Metrics Used:")
        lines.append(f"  Words Per Minute:           {metrics.get('wpm', 0):.1f}")
        lines.append(f"  Fillers Per Minute:         {metrics.get('fillers_per_min', 0):.2f}")
        lines.append(f"  Long Pauses Per Minute:     {metrics.get('long_pauses_per_min', 0):.2f}")
        lines.append(f"  Pause Variability:          {metrics.get('pause_variability', 0):.3f}")
        lines.append(f"  Speech Rate Variability:    {metrics.get('speech_rate_variability', 0):.3f}")
        lines.append(f"  Vocabulary Richness:        {metrics.get('vocab_richness', 0):.3f}")
        lines.append(f"  Type Token Ratio:           {metrics.get('type_token_ratio', 0):.3f}")
        lines.append(f"  Repetition Ratio:           {metrics.get('repetition_ratio', 0):.3f}")
        lines.append(f"  Mean Utterance Length:      {metrics.get('mean_utterance_length', 0):.1f}")

    # Audio information
    metadata = analysis_data.get("metadata", {})
    lines.append("\nAudio Information:")
    lines.append(f"  Duration:                   {metadata.get('duration_seconds', 0):.2f}s")
    lines.append(f"  Total Words:                {metadata.get('total_words', 0)}")

    # Issues detected
    issues = score_result.get("issues", [])
    if issues:
        lines.append("\nIssues Detected:")
        for issue_info in issues:
            issue_id = issue_info.get("issue", "unknown")
            severity = issue_info.get("severity", "info")
            root_cause = issue_info.get("root_cause", "")
            score_impact = issue_info.get("score_impact", 0)
            lines.append(f"  [{severity.upper()}] {issue_id}: {root_cause}")
            lines.append(f"         (Impact: -{score_impact} points)")

    lines.append("\n" + "=" * 70)
    return "\n".join(lines)


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: python scorer.py <analysis_file>")
        print("\nExamples:")
        print("  python scorer.py S01")
        print("  python scorer.py S01.json")
        print("  python scorer.py analysis/S01.json")
        sys.exit(1)

    analysis_file = sys.argv[1]

    try:
        # Load analysis data
        print(f"Loading analysis data from: {analysis_file}")
        analysis_data = load_analysis(analysis_file)

        # Calculate fluency score from raw input metrics
        print("Calculating fluency score from input metrics...")
        score_result = calculate_fluency(analysis_data)

        # Print report
        report = format_fluency_report(score_result, analysis_data)
        print(f"\n{report}")

        return 0

    except FileNotFoundError as e:
        print(f"[ERROR] {str(e)}")
        return 1
    except ValueError as e:
        print(f"[ERROR] Invalid analysis data: {str(e)}")
        return 1
    except Exception as e:
        print(f"[ERROR] Scoring failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    exit_code = main()
    sys.exit(exit_code)
