#!/usr/bin/env python3
"""
Fluency Scorer Script - Calculate fluency score from raw analysis input data

Takes analysis data from JSON file generated by analyzer.py (containing raw input metrics)
and calculates fluency score (0-100) with detailed subscore breakdowns.
"""

import json
import sys
from pathlib import Path

# Add parent directories to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.core.fluency_metrics import calculate_subscores, calculate_fluency_score, detect_issues
from src.utils.config import CONTEXT_CONFIG


def load_analysis(json_path: str) -> dict:
    """Load analysis data from JSON file."""
    json_file = Path(json_path)

    # If relative path, look in analysis directory
    if not json_file.is_absolute() and not json_file.exists():
        research_dir = Path(__file__).parent
        json_file = research_dir / "analysis" / json_path
        if not json_file.exists():
            # Try with .json extension
            json_file = research_dir / "analysis" / f"{json_path}.json"

    if not json_file.exists():
        raise FileNotFoundError(f"Analysis file not found: {json_file}")

    with open(json_file, 'r') as f:
        return json.load(f)


def calculate_fluency(analysis_data: dict) -> dict:
    """
    Calculate fluency score from raw input metrics.

    Args:
        analysis_data: Dictionary from analyzer output (contains input_metrics)

    Returns:
        Dictionary with fluency score and subscores
    """
    # Extract raw input metrics
    metrics = analysis_data.get("input_metrics", {})

    if not metrics:
        raise ValueError("Missing 'input_metrics' in analysis data")

    # Use conversational context config (can be parameterized later)
    context_config = CONTEXT_CONFIG.get("conversational", {
        "pause_tolerance": 1.0,
        "pause_variability_tolerance": 1.0,
    })

    # Calculate subscores from raw input metrics
    subscores, _ = calculate_subscores(metrics, context_config)

    # Calculate overall fluency score
    fluency_score = calculate_fluency_score(subscores, metrics)

    # Detect issues
    issues = detect_issues(subscores, metrics)

    return {
        "fluency_score": fluency_score,
        "subscores": subscores,
        "issues": issues,
        "input_metrics": metrics,  # The raw input metrics used
    }


def format_fluency_report(score_result: dict, analysis_data: dict) -> str:
    """Format fluency scoring results for display."""
    lines = []

    filename = analysis_data.get("metadata", {}).get("filename", "Unknown")
    lines.append(f"Fluency Analysis Report")
    lines.append(f"File: {filename}")
    lines.append("=" * 70)

    # Fluency score
    fluency_score = score_result.get("fluency_score", 0)
    lines.append(f"\nFluency Score: {fluency_score}/100")
    lines.append("-" * 70)

    # Subscores
    subscores = score_result.get("subscores", {})
    if subscores:
        lines.append("\nSubscores (0.0-1.0):")
        lines.append(f"  Speech Rate:       {subscores.get('speech_rate', 0):.2f}")
        lines.append(f"  Pause Structure:   {subscores.get('pause', 0):.2f}")
        lines.append(f"  Filler Dependency: {subscores.get('filler', 0):.2f}")
        lines.append(f"  Rhythmic Stability:{subscores.get('stability', 0):.2f}")
        lines.append(f"  Lexical Quality:   {subscores.get('lexical', 0):.2f}")

    # Input metrics used for calculation
    metrics = score_result.get("input_metrics", {})
    if metrics:
        lines.append("\nInput Metrics Used:")
        lines.append(f"  Words Per Minute:           {metrics.get('wpm', 0):.1f}")
        lines.append(f"  Fillers Per Minute:         {metrics.get('fillers_per_min', 0):.2f}")
        lines.append(f"  Long Pauses Per Minute:     {metrics.get('long_pauses_per_min', 0):.2f}")
        lines.append(f"  Pause Variability:          {metrics.get('pause_variability', 0):.3f}")
        lines.append(f"  Speech Rate Variability:    {metrics.get('speech_rate_variability', 0):.3f}")
        lines.append(f"  Vocabulary Richness:        {metrics.get('vocab_richness', 0):.3f}")
        lines.append(f"  Type Token Ratio:           {metrics.get('type_token_ratio', 0):.3f}")
        lines.append(f"  Repetition Ratio:           {metrics.get('repetition_ratio', 0):.3f}")
        lines.append(f"  Mean Utterance Length:      {metrics.get('mean_utterance_length', 0):.1f}")

    # Audio information
    metadata = analysis_data.get("metadata", {})
    lines.append("\nAudio Information:")
    lines.append(f"  Duration:                   {metadata.get('duration_seconds', 0):.2f}s")
    lines.append(f"  Total Words:                {metadata.get('total_words', 0)}")

    # Issues detected
    issues = score_result.get("issues", [])
    if issues:
        lines.append("\nIssues Detected:")
        for issue_info in issues:
            issue_id = issue_info.get("issue", "unknown")
            severity = issue_info.get("severity", "info")
            root_cause = issue_info.get("root_cause", "")
            score_impact = issue_info.get("score_impact", 0)
            lines.append(f"  [{severity.upper()}] {issue_id}: {root_cause}")
            lines.append(f"         (Impact: -{score_impact} points)")

    lines.append("\n" + "=" * 70)
    return "\n".join(lines)


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: uv run scorer.py <analysis_file>")
        print("\nExamples:")
        print("  uv run scorer.py S01")
        print("  uv run scorer.py S01.json")
        print("  uv run scorer.py analysis/S01.json")
        sys.exit(1)

    analysis_file = sys.argv[1]

    try:
        # Load analysis data
        print(f"Loading analysis data from: {analysis_file}")
        analysis_data = load_analysis(analysis_file)

        # Calculate fluency score from raw input metrics
        print("Calculating fluency score from input metrics...")
        score_result = calculate_fluency(analysis_data)

        # Print report
        report = format_fluency_report(score_result, analysis_data)
        print(f"\n{report}")

        return 0

    except FileNotFoundError as e:
        print(f"[ERROR] {str(e)}")
        return 1
    except ValueError as e:
        print(f"[ERROR] Invalid analysis data: {str(e)}")
        return 1
    except Exception as e:
        print(f"[ERROR] Scoring failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    exit_code = main()
    sys.exit(exit_code)
